const ACCOUNTING_ACCOUNT_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  CODE_NOT_EXISTS: 'CODE_NOT_EXISTS',
  CODE_IS_EMPTY: 'CODE_IS_EMPTY',
  CODE_DUPLICATE: 'CODE_DUPLICATE',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  TYPE_NOT_EXISTS: 'TYPE_NOT_EXISTS',
  TYPE_IS_EMPTY: 'TYPE_IS_EMPTY',
  TYPE_INVALID: 'TYPE_INVALID',
  NATURE_NOT_EXISTS: 'NATURE_NOT_EXISTS',
  NATURE_IS_EMPTY: 'NATURE_IS_EMPTY',
  NATURE_INVALID: 'NATURE_INVALID',
  LEVEL_NOT_EXISTS: 'LEVEL_NOT_EXISTS',
  LEVEL_IS_EMPTY: 'LEVEL_IS_EMPTY',
  LEVEL_INVALID: 'LEVEL_INVALID',
  PARENT_ID_INVALID: 'PARENT_ID_INVALID',
  PARENT_LEVEL_MISMATCH: 'PARENT_LEVEL_MISMATCH'
});

module.exports = { ACCOUNTING_ACCOUNT_VALIDATORS };
