const ACCOUNTING_PERIOD_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  ID_INVALID: 'ID_INVALID',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  YEAR_NOT_EXISTS: 'YEAR_NOT_EXISTS',
  YEAR_IS_EMPTY: 'YEAR_IS_EMPTY',
  YEAR_INVALID: 'YEAR_INVALID',
  MONTH_NOT_EXISTS: 'MONTH_NOT_EXISTS',
  MONTH_IS_EMPTY: 'MONTH_IS_EMPTY',
  MONTH_INVALID: 'MONTH_INVALID'
});

module.exports = { ACCOUNTING_PERIOD_VALIDATORS };
