const ACCOUNTING_VOUCHER_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  ID_INVALID: 'ID_INVALID',
  TYPE_NOT_EXISTS: 'TYPE_NOT_EXISTS',
  TYPE_IS_EMPTY: 'TYPE_IS_EMPTY',
  TYPE_INVALID: 'TYPE_INVALID',
  PERIOD_ID_NOT_EXISTS: 'PERIOD_ID_NOT_EXISTS',
  PERIOD_ID_IS_EMPTY: 'PERIOD_ID_IS_EMPTY',
  PERIOD_ID_INVALID: 'PERIOD_ID_INVALID',
  DATE_NOT_EXISTS: 'DATE_NOT_EXISTS',
  DATE_IS_EMPTY: 'DATE_IS_EMPTY',
  DATE_INVALID: 'DATE_INVALID',
  DESCRIPTION_NOT_EXISTS: 'DESCRIPTION_NOT_EXISTS',
  DESCRIPTION_IS_EMPTY: 'DESCRIPTION_IS_EMPTY',
  LINES_NOT_EXISTS: 'LINES_NOT_EXISTS',
  LINES_INVALID: 'LINES_INVALID',
  LINES_MIN: 'LINES_MIN'
});

module.exports = { ACCOUNTING_VOUCHER_VALIDATORS };
