const BRANCH = Object.freeze({
  VIEW: 'view_branch',
  VIEW_ALL: 'view_branches',
  ADD: 'create_branch',
  UPDATE: 'update_branch',
  DELETE: 'delete_branch'
});

const BRANCH_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  DESC_NOT_EXISTS: 'DESC_NOT_EXISTS',
  DESC_IS_EMPTY: 'DESC_IS_EMPTY',
  ADDRESS_NOT_EXISTS: 'ADDRESS_NOT_EXISTS',
  ADDRESS_IS_EMPTY: 'ADDRESS_IS_EMPTY',
  MUNICIPALITY_NOT_EXISTS: 'MUNICIPALITY_NOT_EXISTS',
  MUNICIPALITY_IS_EMPTY: 'MUNICIPALITY_IS_EMPTY'
});

module.exports = { BRANCH, BRANCH_VALIDATORS };
