const EMPLOYEES_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  EMAIL_IS_EMPTY: 'EMAIL_IS_EMPTY',
  EMAIL_INVALID: 'EMAIL_INVALID',
  HIRE_DATE_NOT_EXISTS: 'HIRE_DATE_NOT_EXISTS',
  HIRE_DATE_IS_EMPTY: 'HIRE_DATE_IS_EMPTY',
  HIRE_DATE_INVALID: 'HIRE_DATE_INVALID',
  POSITION_ID_NOT_EXISTS: 'POSITION_ID_NOT_EXISTS',
  POSITION_ID_IS_EMPTY: 'POSITION_ID_IS_EMPTY',
  BRANCH_ID_NOT_EXISTS: 'BRANCH_ID_NOT_EXISTS',
  BRANCH_ID_IS_EMPTY: 'BRANCH_ID_IS_EMPTY',
  BRANCH_ID_INVALID: 'BRANCH_ID_INVALID',
  ACCESS_EMAIL_NOT_EXISTS: 'ACCESS_EMAIL_NOT_EXISTS',
  ACCESS_EMAIL_IS_EMPTY: 'ACCESS_EMAIL_IS_EMPTY',
  ACCESS_EMAIL_INVALID: 'ACCESS_EMAIL_INVALID',
  ACCESS_PASSWORD_NOT_EXISTS: 'ACCESS_PASSWORD_NOT_EXISTS',
  ACCESS_PASSWORD_IS_EMPTY: 'ACCESS_PASSWORD_IS_EMPTY',
  ACCESS_PASSWORD_TOO_SHORT: 'ACCESS_PASSWORD_TOO_SHORT',
  ACCESS_PRIVILEGES_NOT_EXISTS: 'ACCESS_PRIVILEGES_NOT_EXISTS',
  ACCESS_PRIVILEGES_INVALID: 'ACCESS_PRIVILEGES_INVALID'
});

module.exports = { EMPLOYEES_VALIDATORS };
