const ERR_SECURITY = Object.freeze({
  NOT_PERMISION: 'ERROR_NOT_PERMISSION',
  NOT_PRIVILEGE: 'NOT_PRIVILEGE',
  FORBIDDEN_ROLE_HIERARCHY: 'No tiene permisos para modificar usuarios con ese rol',
  FORBIDDEN_CANNOT_CREATE_SUPERADMIN: 'Solo un superadmin puede crear o elevar a superadmin',
  FORBIDDEN_CANNOT_MODIFY_SUPERADMIN_PRIVILEGES: 'Solo un superadmin puede modificar privilegios de superadmin'
});

const LOGIN = Object.freeze({
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  ERR_LOGIN: 'ERROR_LOGIN_USER'
});

const USER = Object.freeze({
  ERROR_REGISTER_SUPER_USER: 'ERROR_REGISTER_SUPER_USER',
  ERROR_REGISTER_USER: 'ERROR_REGISTER_USER',
  ID_NOT_EXISTS: 'ID_NOT_EXISTS'
});

const SESSION = Object.freeze({
  NOT_SESION: 'NOT_SESION',
  NOT_TOKEN: 'NOT_TOKEN',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ERROR_ID_TOKEN: 'ERROR_ID_TOKEN',
  USER_ID_TOKEN_NOT_EXISTS: 'USER_ID_TOKEN_NOT_EXISTS'
});

const REGISTER = Object.freeze({
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  NAME_LENGTH_ERROR: 'NAME_LENGTH_ERROR',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  EMAIL_EMPTY: 'EMAIL_EMPTY',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  PASSWORD_NOT_EXISTS: 'PASSWORD_NOT_EXISTS',
  PASSWORD_EMPTY: 'PASSWORD_EMPTY',
  PASSWORD_LENGTH_ERROR: 'PASSWORD_LENGTH_ERROR',
  ROLE_NOT_EXISTS: 'ROLE_NOT_EXISTS',
  ROLE_IS_EMPTY: 'ROLE_IS_EMPTY',
  ROLE_INVALID: 'ROLE_INVALID'
});

module.exports = { ERR_SECURITY, LOGIN, USER, SESSION, REGISTER };
