const EXPENSE_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  BRANCH_ID_NOT_EXISTS: 'BRANCH_ID_NOT_EXISTS',
  BRANCH_ID_IS_EMPTY: 'BRANCH_ID_IS_EMPTY',
  EXPENSE_TYPE_ID_NOT_EXISTS: 'EXPENSE_TYPE_ID_NOT_EXISTS',
  EXPENSE_TYPE_ID_IS_EMPTY: 'EXPENSE_TYPE_ID_IS_EMPTY',
  TRANS_DATE_NOT_EXISTS: 'TRANS_DATE_NOT_EXISTS',
  TRANS_DATE_IS_EMPTY: 'TRANS_DATE_IS_EMPTY',
  TRANS_DATE_INVALID: 'TRANS_DATE_INVALID',
  EXPENSE_AMOUNT_NOT_EXISTS: 'EXPENSE_AMOUNT_NOT_EXISTS',
  EXPENSE_AMOUNT_IS_EMPTY: 'EXPENSE_AMOUNT_IS_EMPTY',
  EXPENSE_AMOUNT_INVALID: 'EXPENSE_AMOUNT_INVALID'
});

module.exports = { EXPENSE_VALIDATORS };
