const LOYALTY_ERRORS = {
  LOYALTY_CONFIG_NOT_FOUND: 'LOYALTY_CONFIG_NOT_FOUND',
  LOYALTY_CONFIG_INACTIVE: 'LOYALTY_CONFIG_INACTIVE',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  POINTS_BELOW_MINIMUM: 'POINTS_BELOW_MINIMUM',
  POINTS_EXCEED_MAX_DISCOUNT: 'POINTS_EXCEED_MAX_DISCOUNT',
  POINTS_EXCEED_MAX_LIMIT: 'POINTS_EXCEED_MAX_LIMIT',
  CUSTOMER_POINTS_NOT_FOUND: 'CUSTOMER_POINTS_NOT_FOUND',
  INVALID_ADJUST_AMOUNT: 'INVALID_ADJUST_AMOUNT',
  ADJUST_WOULD_NEGATIVE_BALANCE: 'ADJUST_WOULD_NEGATIVE_BALANCE'
};

module.exports = { LOYALTY_ERRORS };
