const POSITIONS_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  DESC_NOT_EXISTS: 'DESC_NOT_EXISTS',
  DESC_IS_EMPTY: 'DESC_IS_EMPTY'
});

module.exports = { POSITIONS_VALIDATORS };
