const PRICE_LISTS_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  DISCOUNT_PERCENT_INVALID: 'DISCOUNT_PERCENT_INVALID',
  PRIORITY_INVALID: 'PRIORITY_INVALID'
});

module.exports = { PRICE_LISTS_VALIDATORS };
