const PRODUCTS_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  SKU_NOT_EXISTS: 'SKU_NOT_EXISTS',
  SKU_IS_EMPTY: 'SKU_IS_EMPTY',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  BASE_PRICE_NOT_EXISTS: 'BASE_PRICE_NOT_EXISTS',
  BASE_PRICE_IS_EMPTY: 'BASE_PRICE_IS_EMPTY',
  BASE_PRICE_INVALID: 'BASE_PRICE_INVALID',
  COST_PRICE_INVALID: 'COST_PRICE_INVALID',
  UNIT_OF_MEASURE_INVALID: 'UNIT_OF_MEASURE_INVALID',
  CATEGORY_ID_INVALID: 'CATEGORY_ID_INVALID',
  WEIGHT_INVALID: 'WEIGHT_INVALID'
});

module.exports = { PRODUCTS_VALIDATORS };
