const PRODUCT_PRICES_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  ID_INVALID: 'ID_INVALID',
  PRODUCT_ID_NOT_EXISTS: 'PRODUCT_ID_NOT_EXISTS',
  PRODUCT_ID_IS_EMPTY: 'PRODUCT_ID_IS_EMPTY',
  PRODUCT_ID_INVALID: 'PRODUCT_ID_INVALID',
  PRICE_LIST_ID_NOT_EXISTS: 'PRICE_LIST_ID_NOT_EXISTS',
  PRICE_LIST_ID_IS_EMPTY: 'PRICE_LIST_ID_IS_EMPTY',
  PRICE_LIST_ID_INVALID: 'PRICE_LIST_ID_INVALID',
  PRICE_NOT_EXISTS: 'PRICE_NOT_EXISTS',
  PRICE_IS_EMPTY: 'PRICE_IS_EMPTY',
  PRICE_INVALID: 'PRICE_INVALID',
  MIN_QUANTITY_INVALID: 'MIN_QUANTITY_INVALID'
});

module.exports = { PRODUCT_PRICES_VALIDATORS };
