const PRODUCT_STOCKS_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  PRODUCT_ID_NOT_EXISTS: 'PRODUCT_ID_NOT_EXISTS',
  PRODUCT_ID_IS_EMPTY: 'PRODUCT_ID_IS_EMPTY',
  PRODUCT_ID_INVALID: 'PRODUCT_ID_INVALID',
  BRANCH_ID_NOT_EXISTS: 'BRANCH_ID_NOT_EXISTS',
  BRANCH_ID_IS_EMPTY: 'BRANCH_ID_IS_EMPTY',
  BRANCH_ID_INVALID: 'BRANCH_ID_INVALID',
  QUANTITY_INVALID: 'QUANTITY_INVALID',
  MIN_STOCK_INVALID: 'MIN_STOCK_INVALID',
  MAX_STOCK_INVALID: 'MAX_STOCK_INVALID',
  LAST_COUNT_DATE_INVALID: 'LAST_COUNT_DATE_INVALID'
});

module.exports = { PRODUCT_STOCKS_VALIDATORS };
