'use strict';

const SUPPLIERS_VALIDATORS = Object.freeze({
  ID_NOT_EXISTS: 'ID_NOT_EXISTS',
  ID_IS_EMPTY: 'ID_IS_EMPTY',
  ID_NOT_INTEGER: 'ID_NOT_INTEGER',
  NAME_NOT_EXISTS: 'NAME_NOT_EXISTS',
  NAME_IS_EMPTY: 'NAME_IS_EMPTY',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  TRADE_NAME_TOO_LONG: 'TRADE_NAME_TOO_LONG',
  TAX_ID_TOO_LONG: 'TAX_ID_TOO_LONG',
  CONTACT_NAME_TOO_LONG: 'CONTACT_NAME_TOO_LONG',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  EMAIL_IS_EMPTY: 'EMAIL_IS_EMPTY',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PHONE_TOO_LONG: 'PHONE_TOO_LONG',
  MOBILE_TOO_LONG: 'MOBILE_TOO_LONG',
  ADDRESS_TOO_LONG: 'ADDRESS_TOO_LONG',
  MUNICIPALITY_ID_NOT_INTEGER: 'MUNICIPALITY_ID_NOT_INTEGER',
  POSTAL_CODE_TOO_LONG: 'POSTAL_CODE_TOO_LONG',
  WEBSITE_TOO_LONG: 'WEBSITE_TOO_LONG',
  PAYMENT_TERMS_TOO_LONG: 'PAYMENT_TERMS_TOO_LONG',
  CREDIT_LIMIT_NOT_DECIMAL: 'CREDIT_LIMIT_NOT_DECIMAL',
  CREDIT_LIMIT_NEGATIVE: 'CREDIT_LIMIT_NEGATIVE',
  IS_ACTIVE_NOT_BOOLEAN: 'IS_ACTIVE_NOT_BOOLEAN'
});

module.exports = {
  SUPPLIERS_VALIDATORS
};
