module.exports = {
  data: [
    { name: 'Matriz', address: 'Km 5. Carretera Tejupilco Amatepec', municipality_id: 743, phone: '(999) 999-9999' },
    { name: 'Tejupilco', address: 'Prolongación 27 de Septiembre s/n,Col Juárez', municipality_id: 743, phone: '' },
    { name: 'Amatepec', address: 'Miguel Hidalgo No. 23 Col. Centro', municipality_id: 669, phone: '' },
    { name: 'Palmar Chico', address: 'Av. Vicente Guerrero No. 20', municipality_id: 669, phone: '' },
    { name: 'Temascaltepec', address: 'Abasolo No. 12 Col. Centro', municipality_id: 747, phone: '' },
    { name: 'Almoloya', address: 'Conocido Almoloya de Alquisiras', municipality_id: 665, phone: '' },
    { name: 'SP Limon', address: 'Frente a la Plaza Principal, San Pedro Limón', municipality_id: 766, phone: '' },
    { name: 'Altamirano', address: 'Av. Lázaro Cárdenas No. 517 Pungarabato', municipality_id: 84, phone: '' },
    { name: 'Santo Tomas', address: 'Conocido Santo Tomas de los Platanos', municipality_id: 739, phone: '' },
    { name: 'Texcaltitlan', address: 'Conocido Texcaltitlan', municipality_id: 758, phone: '' },
    { name: 'Cutzamala', address: 'Eusebio Almose No. 25 Col. Centro, Cutzamala de Pinzón, Gro.', municipality_id: 398, phone: '' },
    { name: 'Luvianos', address: 'Francisco I. Madero s/n Col. Centro', municipality_id: 784, phone: '' },
    { name: 'Colorines', address: 'Av. José Guadarrama No. 100 Col. Centro', municipality_id: 771, phone: '' },
    { name: 'Arcelia', address: 'Av. Altamirano s/n Col. Centro', municipality_id: 378, phone: '' },
    { name: 'Villa Victoria', address: 'CRUCERO RUMBO A LAS  PEÑAS', municipality_id: 775, phone: '' },
    { name: 'SULTEPEC', address: 'SULTEPEC  EDO. MEX.', municipality_id: 741, phone: '' },
    { name: 'Tlapehuala', address: 'Portal Mercaderes No. 1 frente al Zocalo', municipality_id: 438, phone: '' },
    { name: 'ZACAPUATO', address: 'DOM CON ZACAPUATO', municipality_id: 398, phone: '' },
    { name: 'BEJUCOS', address: 'PLAZA CENTRAL', municipality_id: 743, phone: '' },
    { name: 'COYUCA', address: 'DOM. CON. EN LA ENTRADA', municipality_id: 84, phone: '' },
    { name: 'ZACAZONAPAN', address: 'DOM. CON. ENTRADA PRINCIPAL', municipality_id: 777, phone: '' },
    { name: 'CENTRO', address: 'CENTRO DE TEJUPILCO', municipality_id: 743, phone: '' },
    { name: 'COATEPEC', address: 'COATEPEC', municipality_id: 682, phone: '' },
    { name: 'SN SIMON DE GRO', address: 'SN SIMON DE GRO', municipality_id: 738, phone: '' },
    { name: 'VALLE DE BRAVO', address: 'JUAREZ No 537', municipality_id: 771, phone: '' },
    { name: 'Ixtapan', address: 'Conocido ixtapan de la sal', municipality_id: 701, phone: '' },
    { name: 'ESTELARIS', address: 'AV. 27 DE SEPTIEMBRE', municipality_id: 743, phone: '' },
    { name: 'LUVIANOS 2', address: 'CENTRO', municipality_id: 784, phone: '' },
    { name: 'VILLA', address: 'AV. LAZARO CARDENAS S.N', municipality_id: 775, phone: '' },
    { name: 'Amanalco', address: 'Av. Onesimo Reyes S/N', municipality_id: 668, phone: '' },
    { name: 'EL ARCO', address: 'EL ARCO VALLE DE BRAVO', municipality_id: 771, phone: '' },
    { name: 'STO TOMAS 2', address: 'SANTO TOMAS DE LOS PLATANOS', municipality_id: 739, phone: '' },
    { name: 'SAN FRANCISCO', address: 'AVENIDA PRINCIPAL S/N', municipality_id: 693, phone: '' },
    { name: 'VILLA GRO', address: 'AV. 5 DE MAYO SIN NUMERO', municipality_id: 651, phone: '' },
    { name: 'TENANCINGO', address: 'PASEO DE LOS INSURGENTES S/N', municipality_id: 749, phone: '' },
    { name: 'Donato Guerra', address: 'km1 desviacion a valle de bravo', municipality_id: 693, phone: '' },
    { name: 'adb', address: 'abv', municipality_id: 171, phone: '' },
    { name: 'otra sucursal', address: 'mi dirección', municipality_id: 2, phone: '(132) 222-2222' },
    { name: 'sucursal de prueba', address: 'pilcaya', municipality_id: 420, phone: '' }
  ]
};
