module.exports = {
  data: [
    {
      id: 1,
      sku: 'SAL-001',
      barcode: '7501234567001',
      name: 'Sala Esquinera Moderna',
      description: 'Sala esquinera con diseño moderno, tapizado en tela de alta calidad',
      short_description: 'Sala esquinera moderna',
      category_id: 4,
      unit_of_measure: 'piece',
      cost_price: 8500.00,
      base_price: 12999.00,
      weight: 85.00,
      dimensions: JSON.stringify({ length: 280, width: 180, height: 90 }),
      images: JSON.stringify(['sala-esquinera-1.jpg', 'sala-esquinera-2.jpg']),
      is_active: true,
      is_featured: true,
      seo_title: 'Sala Esquinera Moderna - Mueblería',
      seo_description: 'Sala esquinera con diseño moderno',
      seo_keywords: 'sala, esquinera, moderna, muebles'
    },
    {
      id: 2,
      sku: 'COM-001',
      barcode: '7501234567002',
      name: 'Comedor 6 Sillas Madera',
      description: 'Comedor de madera maciza con 6 sillas tapizadas',
      short_description: 'Comedor 6 sillas',
      category_id: 3,
      unit_of_measure: 'piece',
      cost_price: 6500.00,
      base_price: 9999.00,
      weight: 65.00,
      dimensions: JSON.stringify({ length: 180, width: 90, height: 76 }),
      images: JSON.stringify(['comedor-6-sillas.jpg']),
      is_active: true,
      is_featured: true,
      seo_title: 'Comedor 6 Sillas Madera',
      seo_description: 'Comedor de madera con 6 sillas',
      seo_keywords: 'comedor, madera, 6 sillas'
    },
    {
      id: 3,
      sku: 'REC-001',
      barcode: '7501234567003',
      name: 'Recámara King Size Completa',
      description: 'Recámara completa: cama king size, 2 burós, cómoda y espejo',
      short_description: 'Recámara king completa',
      category_id: 8,
      unit_of_measure: 'piece',
      cost_price: 12000.00,
      base_price: 18999.00,
      weight: 120.00,
      dimensions: JSON.stringify({ length: 200, width: 180, height: 120 }),
      images: JSON.stringify(['recamara-king-1.jpg', 'recamara-king-2.jpg']),
      is_active: true,
      is_featured: true,
      seo_title: 'Recámara King Size Completa',
      seo_description: 'Recámara completa king size',
      seo_keywords: 'recamara, king size, completa'
    },
    {
      id: 4,
      sku: 'COL-001',
      barcode: '7501234567004',
      name: 'Colchón Matrimonial Ortopédico',
      description: 'Colchón matrimonial con soporte ortopédico y memory foam',
      short_description: 'Colchón matrimonial',
      category_id: 17,
      unit_of_measure: 'piece',
      cost_price: 3500.00,
      base_price: 5999.00,
      weight: 25.00,
      dimensions: JSON.stringify({ length: 190, width: 140, height: 25 }),
      images: JSON.stringify(['colchon-matrimonial.jpg']),
      is_active: true,
      is_featured: false,
      seo_title: 'Colchón Matrimonial Ortopédico',
      seo_description: 'Colchón matrimonial ortopédico',
      seo_keywords: 'colchon, matrimonial, ortopedico'
    },
    {
      id: 5,
      sku: 'REF-001',
      barcode: '7501234567005',
      name: 'Refrigerador 18 Pies',
      description: 'Refrigerador de 18 pies cúbicos con dispensador de agua',
      short_description: 'Refrigerador 18 pies',
      category_id: 2,
      unit_of_measure: 'piece',
      cost_price: 9000.00,
      base_price: 13999.00,
      weight: 75.00,
      dimensions: JSON.stringify({ length: 70, width: 70, height: 180 }),
      images: JSON.stringify(['refrigerador-18.jpg']),
      is_active: true,
      is_featured: true,
      seo_title: 'Refrigerador 18 Pies',
      seo_description: 'Refrigerador 18 pies con dispensador',
      seo_keywords: 'refrigerador, 18 pies, linea blanca'
    },
    {
      id: 6,
      sku: 'LAV-001',
      barcode: '7501234567006',
      name: 'Lavadora Automática 20 Kg',
      description: 'Lavadora automática de 20 kg con múltiples programas de lavado',
      short_description: 'Lavadora 20 kg',
      category_id: 2,
      unit_of_measure: 'piece',
      cost_price: 7500.00,
      base_price: 11999.00,
      weight: 45.00,
      dimensions: JSON.stringify({ length: 60, width: 60, height: 100 }),
      images: JSON.stringify(['lavadora-20kg.jpg']),
      is_active: true,
      is_featured: false,
      seo_title: 'Lavadora Automática 20 Kg',
      seo_description: 'Lavadora automática 20 kg',
      seo_keywords: 'lavadora, automatica, 20 kg'
    },
    {
      id: 7,
      sku: 'TV-001',
      barcode: '7501234567007',
      name: 'Televisor LED 55 Pulgadas Smart',
      description: 'Televisor LED 55 pulgadas con Smart TV y resolución 4K',
      short_description: 'TV LED 55" Smart',
      category_id: 1,
      unit_of_measure: 'piece',
      cost_price: 6000.00,
      base_price: 9499.00,
      weight: 15.00,
      dimensions: JSON.stringify({ length: 124, width: 8, height: 72 }),
      images: JSON.stringify(['tv-55-smart.jpg']),
      is_active: true,
      is_featured: true,
      seo_title: 'Televisor LED 55 Pulgadas Smart',
      seo_description: 'TV LED 55 pulgadas Smart 4K',
      seo_keywords: 'television, led, 55 pulgadas, smart tv, 4k'
    },
    {
      id: 8,
      sku: 'BIC-001',
      barcode: '7501234567008',
      name: 'Bicicleta Montaña R29',
      description: 'Bicicleta de montaña rodada 29, 21 velocidades, frenos de disco',
      short_description: 'Bicicleta montaña R29',
      category_id: 7,
      unit_of_measure: 'piece',
      cost_price: 4500.00,
      base_price: 7499.00,
      weight: 14.00,
      dimensions: JSON.stringify({ length: 180, width: 60, height: 100 }),
      images: JSON.stringify(['bicicleta-r29.jpg']),
      is_active: true,
      is_featured: false,
      seo_title: 'Bicicleta Montaña R29',
      seo_description: 'Bicicleta de montaña rodada 29',
      seo_keywords: 'bicicleta, montaña, r29'
    },
    {
      id: 9,
      sku: 'MUE-001',
      barcode: '7501234567009',
      name: 'Ropero 3 Puertas con Espejo',
      description: 'Ropero de 3 puertas con espejo central y cajones inferiores',
      short_description: 'Ropero 3 puertas',
      category_id: 6,
      unit_of_measure: 'piece',
      cost_price: 5500.00,
      base_price: 8499.00,
      weight: 70.00,
      dimensions: JSON.stringify({ length: 150, width: 55, height: 200 }),
      images: JSON.stringify(['ropero-3-puertas.jpg']),
      is_active: true,
      is_featured: false,
      seo_title: 'Ropero 3 Puertas con Espejo',
      seo_description: 'Ropero 3 puertas con espejo',
      seo_keywords: 'ropero, 3 puertas, espejo'
    },
    {
      id: 10,
      sku: 'INF-001',
      barcode: '7501234567010',
      name: 'Litera Infantil con Escritorio',
      description: 'Litera infantil con escritorio integrado y escalera lateral',
      short_description: 'Litera infantil',
      category_id: 11,
      unit_of_measure: 'piece',
      cost_price: 6000.00,
      base_price: 9299.00,
      weight: 55.00,
      dimensions: JSON.stringify({ length: 200, width: 100, height: 180 }),
      images: JSON.stringify(['litera-infantil.jpg']),
      is_active: true,
      is_featured: false,
      seo_title: 'Litera Infantil con Escritorio',
      seo_description: 'Litera infantil con escritorio',
      seo_keywords: 'litera, infantil, escritorio'
    }
  ]
};
