module.exports = {
  data: [
    {
      id: 1,
      name: 'Muebles del Norte S.A. de C.V.',
      trade_name: 'Muebles del Norte',
      tax_id: 'MNO850101ABC',
      contact_name: 'Roberto García',
      email: 'ventas@mueblesdelnorte.com',
      phone: '8183456789',
      mobile: '8111234567',
      address: 'Av. Industrial 1500, Col. Industrial',
      municipality_id: 1,
      postal_code: '64550',
      website: 'https://mueblesdelnorte.com',
      payment_terms: '30 días',
      credit_limit: 150000.00,
      notes: 'Proveedor principal de salas y comedores',
      is_active: true
    },
    {
      id: 2,
      name: 'Distribuidora de Colchones Premium S.A.',
      trade_name: 'Colchones Premium',
      tax_id: 'DCP900215XYZ',
      contact_name: 'María López',
      email: 'pedidos@colchonespremium.mx',
      phone: '5556789012',
      mobile: '5512345678',
      address: 'Calle Reforma 250, Col. Centro',
      municipality_id: 2,
      postal_code: '06600',
      website: 'https://colchonespremium.mx',
      payment_terms: '15 días',
      credit_limit: 100000.00,
      notes: 'Especialista en colchones y bases',
      is_active: true
    },
    {
      id: 3,
      name: 'Electrodomésticos Nacionales S. de R.L.',
      trade_name: 'ElectroNac',
      tax_id: 'ENA880520DEF',
      contact_name: 'Carlos Hernández',
      email: 'ventas@electronac.com',
      phone: '3336547890',
      mobile: '3312098765',
      address: 'Blvd. Tlaquepaque 890, Zona Industrial',
      municipality_id: 3,
      postal_code: '45500',
      website: 'https://electronac.com',
      payment_terms: '45 días',
      credit_limit: 200000.00,
      notes: 'Línea blanca y electrónicos',
      is_active: true
    },
    {
      id: 4,
      name: 'Importadora de Muebles Finos S.A.',
      trade_name: 'IMF Muebles',
      tax_id: 'IMF950830GHI',
      contact_name: 'Ana Martínez',
      email: 'contacto@imfmuebles.com',
      phone: '4421234567',
      mobile: '4429876543',
      address: 'Parque Industrial El Marqués, Nave 15',
      municipality_id: 4,
      postal_code: '76240',
      website: 'https://imfmuebles.com',
      payment_terms: '60 días',
      credit_limit: 250000.00,
      notes: 'Muebles importados de alta gama',
      is_active: true
    },
    {
      id: 5,
      name: 'Textiles y Tapicería Industrial S.A.',
      trade_name: 'TexTap',
      tax_id: 'TTI920610JKL',
      contact_name: 'Luis Sánchez',
      email: 'ventas@textap.mx',
      phone: '2222345678',
      mobile: '2221098765',
      address: 'Corredor Industrial 500',
      municipality_id: 5,
      postal_code: '72000',
      website: null,
      payment_terms: '30 días',
      credit_limit: 75000.00,
      notes: 'Telas y materiales para tapicería',
      is_active: true
    }
  ]
};
